require:
  - rubocop-performance

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

Naming/FileName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5.0
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable